config/routes.rb
MyBlog::Application.routes.draw do

  devise_for :users
  resources :posts
  root to: "posts#new"

  

end

app/models/post.rb
class Post < ActiveRecord::Base

has_attached_file :photo, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/

validates_attachment_presence :photo
validates_attachment_size :photo, :less_than => 5.megabytes
validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/png']

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :username
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
before_filter :authenticate_user!

  def new
    @post = Post.new
  end

 def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

def update
  @post = Post.find(params[:id])

  if @post.update(params[:post].permit(:title, :text))
    redirect_to @post
  else
    render 'edit'
  end
 end
 
def create
    @post = Post.new params.require(:post).permit([:title, :text, :photo])

    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

 def edit
  @post = Post.find(params[:id])
 end

  def show
    @post = Post.find(params[:id])
  end

  def index
    @post = Post.all
  end
end


  private

  def post_params
  	params.require(:post).permit(:title, :text)
  end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Awesome Ideas" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

<%= link_to new_user_session_path, :class => "dropdown-toggle", :data => {:toggle=>"dropdown"} do %>
  Sign-In <b class="caret"></b>
<% end %>
<%= link_to "Sign Out", destroy_user_session_path, :method => :delete %>
<br>
<br>

    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/posts/_form.html.erb
 <%= form_for @post, :html => { :multipart => true } do |f| %>
    <% if @post.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@post.errors.count, "error") %> prohibited
            this post from being saved:</h2>
          <ul>
            <% @post.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <p>
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </p>

    <p>
      <%= f.label :text %><br>
      <%= f.text_area :text %>
    </p>


    <%= f.label :photo %>
    <%= f.file_field :photo %>

    <p>
      <%= f.submit %>
    </p>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Ideas</h1> <h4>(Changed your mind?)</h4>
 
<%= render 'form' %>
 
<%= link_to 'Back', posts_path %>
<%= link_to 'New', new_post_path %>

app/views/posts/index.html.erb
<h1>Awesome Ideas</h1>
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <%= link_to 'New', new_post_path %>

  <% @post.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.text %></td>
        <td><%= image_tag post.photo.url(:thumb) %></td>        
        <td><%= link_to 'Show', post_path(post) %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Delete', post_path(post), method: :delete, data: { confirm: 'Are you sure?'} %>
        </td>
      </tr>
  <% end %>
</table>

app/views/posts/new.html.erb
<h1>Awesome Ideas</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p>
	<strong>Title:</strong>
	<%= @post.title %>
	
</p>
	<strong>Text:</strong>
<%= @post.text %>
</p>

<%= image_tag @post.photo.url(:medium) %>

<%= link_to 'Back', posts_path %>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>